---
- hosts: compute
  tasks:
  - name: Install packages
    apt: name={{ item }}
    with_items:
     - swift
     - python-swiftclient
     - swift-account
     - swift-container
     - swift-object
  - name: create configuration files
    template: src=role/swift/templates/account-server.conf dest=/etc/swift/account-server.conf owner=swift group=swift
  - name: create configuration files
    template: src=role/swift/templates/container-server.conf dest=/etc/swift/container-server.conf owner=swift group=swift
  - name: create configuration files
    template: src=role/swift/templates/object-server.conf dest=/etc/swift/object-server.conf owner=swift group=swift
  - name: create configuration files
    template: src=role/swift/templates/rsyncd.conf dest=/etc/rsyncd.conf 
